### ISSUE TITLE
tf.name_scope & variables

### ISSUE THREAD

**Issue by pshvechikov** [vahidk/EffectiveTensorflow#12]
`TensorFlow introduces two different context managers to alter the name of tensors and variables. The first is tf.name_scope which modifies the name of tensors:` 

This sentence might mean that `tf.name_scope ` does not modify the name of variables. 

However, when  `tf.Variable` constructor is called  the name of Variable is also altered. 

```
with tf.name_scope("scope"):
    a = tf.get_variable(name="a", shape=[])
    print(a.name)  # prints "a:0"

    b = tf.constant(1, name="b")
    print(b.name)  # prints "scope/b:0"
    
    c = tf.Variable(tf.zeros([]), name="c")
    print(c.name)  # prints "scope/c:0"
```

What do you think, is this point worth to be included in your wonderful guide?

**Comment by vahidk** [comment]
Thanks for the suggestion. I fixed this at e0db052.
