### ISSUE TITLE
TensorFlow data input

### ISSUE THREAD

**Issue by ljb23** [vahidk/EffectiveTensorflow#14]
Thank you for writing such a great TensorFlow tutorial.  Do you plan to discuss best practices for effectively feeding data while training?  I really hope you do, as this seems to be something a lot of beginners really struggle with.

**Comment by vahidk** [comment]
I have talked a bit about it in the estimator API, and there's code example in the provided code. I may add another item dedicated to this at some point. Thanks for the suggestion.
