### ISSUE TITLE
Multi-GPU code

### ISSUE THREAD

**Issue by DrSleep** [vahidk/EffectiveTensorflow#3]
Hello!

I have a question regarding the multi-gpu recipe. 
Shouldn't it be something along the lines 
```python 
out_split.append(fn(**{k : v[i] for k,v in in_splits.iteritems()}))
```
 instead of just 
```python
out_split.append(fn(**kwargs))
```
 in the `make_parallel` function?

Awesome work, by the way!

**Comment by vahidk** [comment]
You are absolutely right. I applied your patch at fbe7f78. Feel free to send pull requests if you spot any errors.

Thanks!
