### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [vahidk/EffectiveTensorflow#32]
Could you please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Thanks!

**Comment by mbrukman** [comment]
@vahidk — you closed the bug without comment, but I also didn't see a `LICENSE` file added to the repo. Can you please clarify your thoughts on this?

**Comment by vahidk** [comment]
It seemed like a mass copy pasted message that's why I didn't comment. This repo is a tutorial. What percentage of tutorials/ebooks come with an open source license?

**Comment by mbrukman** [comment]
The question is not whether it's a tutorial or a production system; the question is what can users do with this content (e.g., can they redistribute it? can they extend it? can they modify or update it? etc.). From a copyright perspective, a lack of a license prohibits these activities and others.

Please see the docs I quoted from GitHub regarding what a lack of a license does for this repo; they have an entire site on this: https://choosealicense.com, specifically, please take a look at https://choosealicense.com/no-permission/ which describes this situation in detail.

My comment above got a :+1: vote from another user, so clearly it's relevant and important for other users of your repos. Please consider adding an open-source license to your repositories.

**Comment by vahidk** [comment]
My point is, it's a tutorial. It could be on Medium and you wouldn't comment on having a license file for it. I'm using Github as a publishing platform. The way it currently works is that people who want to use this material just send me an email and I usually tell them it's okey to use to this material. So it's on a case by case basis. If you really are interested to use this material personally we can discuss privately. I might add a license later. I just am not sure what's a suitable license at this point.

**Comment by mbrukman** [comment]
Thanks for the clarification.

FWIW, https://choosealicense.com has options both for code (applicable to https://github.com/vahidk/TensorflowFramework) as well as this repo (which isn't code). E.g., Creative Commons licenses are widely used for text/documentation. Of course, the choice of license (or to have no license, defaulting to "all rights reserved" copyright) is up to you, and it sounds like you've chosen to do that and handle exceptions on a case-by-case basis.
