### ISSUE TITLE
 sel_sum_logprobs = tf.log([[1.] + [0.] * (beam_width - 1)])

### ISSUE THREAD

**Issue by yeshenpy** [vahidk/EffectiveTensorflow#34]
Hi
In beam seach , tf.log(0.) is - inf ,is it right? so why use  sel_sum_logprobs = tf.log([[1.] + [0.] * (beam_width - 1)])

**Comment by vahidk** [comment]
I don't understand the question. Is the question why probability of other initial tokens except first one is set to zero? Because at the beginning we have only one token.

**Comment by yeshenpy** [comment]
log(0.0) is Nan  , is it right ?

**Comment by yeshenpy** [comment]
I think this is bug of your code.  that'all .  thank you .

Vahid Kazemi <notifications@github.com> 于2019年8月8日周四 下午1:15写道：
