### ISSUE TITLE
sel_sum_logprobs = tf.log([[1.] + [0.] * (beam_width - 1)])  in beam seach 

### ISSUE THREAD

**Issue by yeshenpy** [vahidk/EffectiveTensorflow#35]
Question one :
       if beam_width is 3 , why the first is  1.  and the other is 0.0 ? why we set like this instead of  all set to 1 or to 0 ?
Question two:
         

> import tensorflow as tf
a = tf.log([[1.] + [0.] * (3 - 1)])
with tf.Session() as sess:
    print(sess.run(a))

the result is 
`[[  0. -inf -inf]]`

log(0) is Nan , is it right ?is it a bug ?

Question three :

how  update_fn() defined ? in beam search ,any example can provide ?

**Comment by vahidk** [comment]
Please use stackoverflow for these kind of questions. This is not an issue.
